### ISSUE TITLE
Recommendations on CORS headers

### ISSUE THREAD

**Issue by Utopiah** [bfren/docker-nginx-webdav#91]
Hi, thanks for the image. It works well and is very convenient to setup. I managed to make it work and you can see the result at webdav://webdav.benetou.fr and mounted remotely via `davfs`.

Unfortunately when I try to access it remotely via the browser via e.g https://fabien.benetou.fr/pub/home/future_of_text_demo/engine/webdav.html but unfortunately encounter a CORS error. Surprisingly enough yesterday I don't remember encountering that problem.

Anyway here is the reverse proxy configuration :

```
server
{
    add_header Access-Control-Allow-Origin *;
    server_name webdav.benetou.fr;
    location / {
        proxy_pass http://webdav_webdav_1;
        include conf.d/proxy/pass.conf;
    }
    include conf.d/ssl/ssl.conf;
    ssl_certificate /etc/letsencrypt/live/webdav.benetou.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/webdav.benetou.fr/privkey.pem;
}

```

The client I'm using is https://github.com/perry-mitchell/webdav-client/#cors with a link to its CORS mention.

What additional configuration could I add either to the image itself or to the reverse proxy to allow CORS through WebDAV and be able to use https://webdav.benetou.fr on another subdomain e.g https://fabien.benetou.fr/pub/home/future_of_text_demo/engine/webdav.html ?

**Comment by bfren** [comment]
Hi @Utopiah I'm not getting a CORS error with https://fabien.benetou.fr/pub/home/future_of_text_demo/engine/webdav.html - did you manage to sort it?

**Comment by Utopiah** [comment]
Hey @bfren, unfortunately not, you still have try `const directoryItems = await client.getDirectoryContents("/");` from the console which then leads to CORS.

**Comment by bfren** [comment]
The header will need to be set in whatever reverse proxy you're using to serve over https - so it looks like you've set it correctly to allow any requests.  There is nothing in this WebDAV image / config that would block CORS afaik.

You could try being specific about the origin domain (probably sensible anyway) by setting Vary: Origin too (a la https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#access-control-allow-origin)?

**Comment by Utopiah** [comment]
Thanks, that was a step but unfortunately still get stuck with things like `Reason: header ‘depth’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response`.

It seems https://www.williamjbowman.com/blog/2021/05/13/enabling-cors-for-nginx-webdav-and-caldav-reverse-proxy/ was not unecessarily complicated after all. I'll try that and report back.

**Comment by bfren** [comment]
Interesting - I only use this image locally with no internet access so it's not a problem for me - if there's something there I could add to the image as a feature I'd be happy to do that.

**Comment by Utopiah** [comment]
Thanks for the suggestion. I applied this linked configuration and it seems to work well. I'll close this for now so that hopefully if others (including me in the future ;) encounter the same problem they can find this. I suggest not touching the default configuration you already use as most people might prefer to configure at the reverse proxy level.
