### ISSUE TITLE
docker-compose.yml example with write access

### ISSUE THREAD

**Issue by Utopiah** [bfren/docker-nginx-webdav#95]
Hello, could you please share an example that would enable `client.putFileContents()` and such functions?

```dockerfile
version: "3.3"

# Very Simple WebDAV server - serves files mounted in /www. There is no authentication, so this should be used behind a reverse proxy, and local only, unless you know what you are doing.
# https://github.com/bfren/docker-nginx-webdav

services:
  webdav:
    environment:
      - WHATEVER="OK"
      #- WEBDAV_ACCESS="rw"
      #- WEBDAV_METHODS="PUT MKCOL COPY MOVE"
    image: bfren/nginx-webdav
    volumes:
      - ./data:/www
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - my_network

networks:
  my_network:
    external: true
```

It does work but if I change `WEBDAV_ACCESS` I get 

`nginx: [emerg] invalid value "all:"rw"" in /etc/nginx/sites/localhost.conf:9` and the server is not accessible.

**Comment by Utopiah** [comment]
I'm now using

```
        - WEBDAV_ACCESS="rw"
        - WEBDAV_METHODS=PUT\ MKCOL\ COPY\ MOVE
```

and the server does start but still getting a 405.

**Comment by Utopiah** [comment]
Also tried everything in, namely "PROPFIND, COPY, MOVE, MKCOL, CONNECT, DELETE, DONE, GET, HEAD, OPTIONS, PATCH, POST, PUT" (with the "\ " escaping) but no change.

**Comment by bfren** [comment]
Hi - the not so deliberate mistake is the inclusion of quotation marks - here is my own compose file:

```Dockerfile
version: "3.8"

services:
  webdav:
    image: bfren/nginx-webdav:latest
    container_name: localhost-transfer
    restart: unless-stopped
    environment:
      - WEBDAV_ACCESS=rw
      - WEBDAV_METHODS=PUT DELETE MKCOL COPY MOVE
    volumes:
      - /data/share/transfer:/www
    networks:
      - proxy
```

And I don't have any issues using / writing / reading.  I will update the Dockerfile to make that clear.

**Comment by Utopiah** [comment]
Thanks indeed that's fixed it!

I'm still getting an error `500` after a warning from  `Attempt to set a forbidden header was denied: Content-Length` (from https://github.com/perry-mitchell/webdav-client ) but that's probably me misusing that client library or who somehow forgot some headers through nginx.
